server:
  port: 8080

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging.level:
  org.apache.zookeeper.ClientCnxn: WARN

zkConnect: 10.211.55.32:2181,10.211.55.32:2182,10.211.55.32:2183
kafkaServerList: 10.211.55.32:9091,10.211.55.32:9092,10.211.55.32:9093
group: my_group
topic: my_story
key: my_dream